root - INFO - Datetime limit: 03/09/2021, 08:15:03
root - INFO - Setting up the instagram and twitter accounts
instabot version: 0.117.0 - INFO - Instabot version: 0.117.0 Started
instabot version: 0.117.0 - DEBUG - Bot imported from /usr/local/lib/python3.7/dist-packages/instabot/bot/bot.py
instabot version: 0.117.0 - DEBUG - Loading uuids
instabot version: 0.117.0 - INFO - Recovery from /home/pi/config/swedishsteelbot_uuid_and_cookie.json: COOKIE False - UUIDs True - TIMING, DEVICE and ...
- user-agent=Instagram 117.0.0.28.123 Android (28/9.0; 420dpi; 1080x1920; OnePlus; ONEPLUS A3003; OnePlus3; qcom; en_US; 180322800)
- phone_id=16b3bc0e-7c7e-49ca-ae29-cc02f4e43fe7
- uuid=cbb173ee-d841-4eb2-a9e8-74a133fe338d
- client_session_id=ffd89e3c-a100-443f-8486-cf2807443c2e
- device_id=android-749f26189b2c42de
instabot version: 0.117.0 - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
instabot version: 0.117.0 - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
instabot version: 0.117.0 - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
instabot version: 0.117.0 - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
instabot version: 0.117.0 - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
instabot version: 0.117.0 - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb081ce30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
instabot version: 0.117.0 - ERROR - Failed to login go to instagram and change your password
instabot version: 0.117.0 - INFO - Username or password is incorrect.
